# Site
name: "David"
title: "David"
description: "Machine Learning, Engineering, Crypto, Investments"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-216126092-1'
disqus: 'davidcjw-github-io'
mailchimp-list: 'https://github.us20.list-manage.com/subscribe?u=33f00d5ed4ddfd9c97df20503&id=5bfc7bf7f6'
include: ["_pages"]
permalink: /:title/
baseurl: ""

# Authors
authors:
  david:
    name: David
    display_name: David
    gravatar: 239872d9a517e20038a782e33d6fcffa
    email: davidcjw@gmail.com
    web: www.davidcjw.com
    twitter: https://twitter.com/davidcjw22
    description: "Machine Learning Engineer; Masters in AI; Closet n3rd; Avid investor; On a FIRE mission"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
